use gtk::glib;
use sourceview5 as sourceview;
use std::{cell::Cell, cell::RefCell, rc::Rc};

use pithos_core::crypto;
use pithos_core::state::DocState;

pub const CODE_LANGUAGES: &[&str] = &[
    "text",
    "yaml",
    "json",
    "bash",
    "python",
    "rust",
    "go",
    "javascript",
    "typescript",
    "sql",
    "hcl",
    "powershell",
    "kql",
    "dockerfile",
    "html",
    "css",
    "c",
    "cpp",
    "java",
    "mermaid",
];

#[derive(Clone)]
pub struct EditorCtx {
    pub window: adw::ApplicationWindow,
    pub notes_list: gtk::ListBox,
    pub search_entry: gtk::SearchEntry,
    pub source_buffer: sourceview::Buffer,
    pub source_view: sourceview::View,
    pub source_panel: gtk::ScrolledWindow,
    pub preview_webview: webkit6::WebView,
    pub preview_panel: gtk::Box,
    pub split: gtk::Paned,
    pub status: gtk::Label,
    pub doc_label: gtk::Label,
    pub dirty_label: gtk::Label,
    pub tags_box: gtk::FlowBox,
    pub tag_entry: gtk::Entry,
    pub state: Rc<RefCell<DocState>>,
    pub vault_folder: Rc<RefCell<String>>,
    pub cached_key: Rc<RefCell<Option<crypto::CachedKey>>>,
    pub save_timeout_id: Rc<Cell<Option<glib::SourceId>>>,
    pub auto_save_timeout_id: Rc<Cell<Option<glib::SourceId>>>,
    pub save_generation: Rc<Cell<u64>>,
    pub saving: Rc<Cell<bool>>,
    pub close_requested: Rc<Cell<bool>>,
    pub vault_file_monitor: Rc<RefCell<Option<gtk::gio::FileMonitor>>>,
    // HIG layout widgets
    pub split_view: adw::OverlaySplitView,
    pub toast_overlay: adw::ToastOverlay,
    pub toolbar: gtk::ScrolledWindow,
    pub tab_view: adw::TabView,
    pub tab_bar: adw::TabBar,
    pub tags_popover: gtk::Popover,
    pub breadcrumbs: gtk::Label,
    pub tag_filter_box: gtk::Box,
    pub meta_label: gtk::Label,
    pub search_bar: gtk::SearchBar,
    pub content_stack: gtk::Stack,
    pub sync_timeout_id: Rc<Cell<Option<glib::SourceId>>>,
    pub search_timeout_id: Rc<Cell<Option<glib::SourceId>>>,
    // Content chrome
    pub content_header: adw::HeaderBar,
    // Find/replace bar
    pub find_bar: gtk::Box,
    pub find_entry: gtk::SearchEntry,
    pub replace_entry: gtk::Entry,
    pub replace_row: gtk::Box,
    pub find_match_label: gtk::Label,
    pub search_context: sourceview::SearchContext,
    pub search_settings: sourceview::SearchSettings,
    // Vault name display
    pub vault_name_label: gtk::Label,
    // Timestamp of last completed vault save (used by file monitor to suppress own-write toasts)
    pub last_save_completed: Rc<Cell<std::time::Instant>>,
    // Split pane position saved before entering zen mode, restored on exit
    pub pre_zen_split_pos: Rc<Cell<i32>>,
}

pub struct ContentPaneWidgets {
    pub toast_overlay: adw::ToastOverlay,
    pub content_toolbar_view: adw::ToolbarView,
    pub content_header: adw::HeaderBar,
    pub doc_label: gtk::Label,
    pub dirty_label: gtk::Label,
    pub toolbar_scroll: gtk::ScrolledWindow,
    pub tab_view: adw::TabView,
    pub tab_bar: adw::TabBar,
    pub breadcrumbs: gtk::Label,
    pub status_label: gtk::Label,
    pub meta_label: gtk::Label,
    pub status_bar: gtk::ActionBar,
    pub source_buffer: sourceview::Buffer,
    pub source_view: sourceview::View,
    pub source_scroll: gtk::ScrolledWindow,
    pub preview_webview: webkit6::WebView,
    pub preview_scroll: gtk::Box,
    pub split: gtk::Paned,
    pub tags_popover: gtk::Popover,
    pub tags_box: gtk::FlowBox,
    pub tag_entry: gtk::Entry,
    pub toolbar_widgets: ToolbarWidgets,
    pub content_stack: gtk::Stack,
    // Find/replace bar
    pub find_bar: gtk::Box,
    pub find_entry: gtk::SearchEntry,
    pub replace_entry: gtk::Entry,
    pub replace_row: gtk::Box,
    pub find_match_label: gtk::Label,
    pub search_context: sourceview::SearchContext,
    pub search_settings: sourceview::SearchSettings,
    // Vault name label
    pub vault_name_label: gtk::Label,
}

pub struct ToolbarWidgets {
    pub undo: gtk::Button,
    pub redo: gtk::Button,
    pub bold: gtk::Button,
    pub italic: gtk::Button,
    pub underline: gtk::Button,
    pub strike: gtk::Button,
    pub code: gtk::Button,
    pub block_popover: gtk::Popover,
    pub block_paragraph: gtk::Button,
    pub block_h1: gtk::Button,
    pub block_h2: gtk::Button,
    pub block_h3: gtk::Button,
    pub block_h4: gtk::Button,
    pub block_h5: gtk::Button,
    pub block_h6: gtk::Button,
    pub block_quote: gtk::Button,
    pub bullet: gtk::Button,
    pub ordered: gtk::Button,
    pub task: gtk::Button,
    pub link: gtk::Button,
    pub table_menu: gtk::MenuButton,
    pub table_popover: gtk::Popover,
    pub table_hover: Rc<Cell<(i32, i32)>>,
    pub table_add_row: gtk::Button,
    pub table_add_col: gtk::Button,
    pub table_align: gtk::Button,
    pub rule: gtk::Button,
    pub fullscreen: gtk::Button,
    pub image: gtk::Button,
    pub code_block_popover: gtk::Popover,
    pub code_languages: Vec<(String, gtk::Button)>,
}
